// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:      
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXsKPbc-7WI3rXN1qjjmUBjErUqeqeOj4',
    appId: '1:435210335416:web:f12207dfdacaa08e34704d',
    messagingSenderId: '435210335416',
    projectId: 'workin-e7be9',
    authDomain: 'workin-e7be9.firebaseapp.com',
    storageBucket: 'workin-e7be9.firebasestorage.app',
    measurementId: 'G-1Y5YLKP2HX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD21FmJH-BXYEszwqxd-2Z10QVtUg5apJ0',
    appId: '1:435210335416:android:718b6ff089f3da7434704d',
    messagingSenderId: '435210335416',
    projectId: 'workin-e7be9',
    storageBucket: 'workin-e7be9.firebasestorage.app',
  );
}
